name: Project stats
description: Collect, process, and generate reports for project stats

inputs:
  pypi-name:
    description: Name of the package distribution on PyPI
    required: true

  start-date:
    description: Start date in YYYY-MM-DD format
    required: false
    default: ''

  end-date:
    description: End date in YYYY-MM-DD format
    required: true
    default: ''

  notebook-file:
    description: File name/path to the notebook to use for the analysis
    required: false
    default: pypi-stats.ipynb

runs:
  using: composite
  steps:
    - shell: bash -l {0}
      run: |
        ls -lRh
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: release/project-stats/environment.yml
        miniforge-version: latest
        activate-environment: project-stats
    - shell: bash -l {0}
      run: |
        python -m ipykernel install --user --name="project-stats"
    - name: Run parametrize notebook
      shell: bash -l {0}
      working-directory: ${{ github.action_path }}
      run: |
        python -c '
        from pathlib import Path

        import papermill as pm
        
        pypi_name = "${{ inputs.pypi-name }}"
        nb_in = Path("${{ inputs.notebook-file }}")
        nb_out = nb_in

        pm.execute_notebook(
            nb_in,
            nb_out,
            parameters=dict(
              pypi_name=pypi_name,
              start_date="${{ inputs.start-date }}" or None,
              end_date="${{ inputs.end-date }}" or None,
            )
        )
        '
    - name: Export notebook
      shell: bash -l {0}
      working-directory: ${{ github.action_path }}
      run: |
        jupyter nbconvert "${{ inputs.notebook-file }}" --to markdown
        jupyter nbconvert "${{ inputs.notebook-file }}" --to html

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: project-stats
        path: |
          **/*.html
          **/*.md
