name: Project stats
description: Collect, process, and generate reports for project stats

inputs:
  pypi-name:
    description: Name of the package distribution on PyPI
    required: true
  notebook-file:
    description: File name/path to the notebook to use for the analysis
    required: false
    default: pypi-stats.ipynb

runs:
  using: composite
  steps:
    - shell: bash -l {0}
      run: |
        ls -lRh
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ${{ github.action_path }}/environment.yml
        miniforge-version: latest
    - name: Run parametrize notebook
      shell: python {0}
      working-directory: ${{ github.action_path }}
      run: |
        from pathlib import Path

        import papermill as pn
        
        pypi_name = "${{ inputs.pypi-name }}"
        nb_in = Path("${{ inputs.notebook-file }}")
        nb_out = nb_in.with_name(pypi_name).with_suffix(nb_in.suffix)

        pm.execute_notebook(
            nb_in,
            nb_out,
            parameters=dict(
              pypi_name=pypi_name,
            )
        )
    - name: Convert notebook to Markdown
      shell: bash -l {0}
      working-directory: ${{ github.action_path }}
      run: |
        jupyter nbconvert "${{ inputs.notebook-file }}" --to markdown
        cat *.md >> $GITHUB_STEP_SUMMARY
