name: Project stats
description: Collect, process, and generate reports for project stats

inputs:
  pypi-name:
    description: Name of the package distribution on PyPI
    required: true
  notebook-file:
    description: File name/path to the notebook to use for the analysis
    required: false
    default: pypi-stats.ipynb

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
    - name: Run parametrize notebook
      shell: python {0}
      run: |
        from pathlib import Path

        import papermill as pn
        
        pypi_name = "${{ inputs.pypi-name }}"
        nb_in = Path("${{ inputs.notebook-file }}")
        nb_out = nb_in.with_name(pypi_name).with_suffix(nb_in.suffix)

        pm.execute_notebook(
            nb_in,
            nb_out,
            parameters=dict(
              pypi_name=pypi_name,
            )
        )