name: Create package

on:

  workflow_call:
    inputs:

      repository:
        description: Full name (user/repo) of the repository to package
        type: string
        required: true

      release-tag:
        description: Version tag of the release
        type: string
        required: true

      pypi-name:
        description: Name of the Python package distribution as it appears on PyPI
        type: string
        required: true

      python-version:
        description: Python version to use
        required: false
        default: '3.9'
        type: string

      test-command:
        description: Command(s) to use to ensure successfull installation
        type: string
        required: true

      test-pypi-url:
        description: URL to the test PyPI index to use
        type: string
        required: false
        default: https://test.pypi.org/simple/

      pip-install-retry-wait-time:
        description: Amount of time (in s) to wait before retrying to run pip install
        type: string
        required: false
        default: "15"

    secrets:

      test-pypi-token:
        description: Auth token for PyPI (test instance)
        required: true

      pypi-token:
        description: Auth token for PyPI
        required: true

defaults:
  run:
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to be packaged
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.release-tag }}

      - name: Set up Conda environment with Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ format('build-{0}-{1}-env', inputs.pypi-name, inputs.release-tag) }}
          python-version: ${{ inputs.python-version }}

      - name: Install (noneditable mode)
        run: |
          pip install --no-cache-dir .

      - name: Check that the installed package has the expected tags
        run: |
          pip show ${{ inputs.pypi-name }} | grep "${{ inputs.release-tag }}"

      - name: Run smoke tests
        working-directory: /tmp
        run: |
          ${{ inputs.test-command }}

      - name: Generate dist files
        run: |
          python setup.py sdist bdist_wheel

      - name: Check that the dist directory's size is below PyPI's maximum
        run: |
          ls -lh dist/*
          _maxsize=100000  # 100 MB
          _dirsize=$(du -s dist/ | cut -f 1) ; echo $_dirsize
          [ "$_dirsize" -lt "$_maxsize" ]

      - name: Upload dist files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  upload-test-pypi:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      TWINE_USERNAME: __token__
      TWINE_NON_INTERACTIVE: "true"
    steps:

     - uses: actions/download-artifact@v3
       with:
         name: dist

     - uses: actions/setup-python@v2
       with:
         python-version: ${{ inputs.python-version }}

     - uses: Install twine
       run: |
         pip install --progress-bar off twine

     - name: Upload dist files to the test PyPI
       env:
         TWINE_PASSWORD: ${{ secrets.test-pypi-token }}
         TWINE_REPOSITORY_URL: ${{ inputs.test-pypi-url }}
       run: |
         twine upload dist/*

  install-test-pypi:
    runs-on: ubuntu-latest
    needs: [upload-test-pypi]

    steps:

     - uses: actions/setup-python@v2
       with:
         python-version: ${{ inputs.python-version }}

     - name: Install ${{ inputs.pypi-name }}==${{ inputs.release-tag }} from test PyPI
       env:
         _wait_time_s: ${{ inputs.pip-install-retry-wait-time }}
       run: |
        until pip install --progress-bar off "${{ inputs.pypi-name }}==${{ inputs.release-tag }}"
        do
            echo "pip install failed; waiting $_wait_time_s seconds"
            sleep "$_wait_time_s"
        done

     - name: Run tests
       run: |
         ${{ inputs.test-command }}

  upload-pypi:
    runs-on: ubuntu-latest
    needs: [install-test-pypi]
    env:
      TWINE_USERNAME: __token__
      TWINE_NON_INTERACTIVE: "true"
    steps:

     - uses: actions/download-artifact@v3
       with:
         name: dist

     - uses: actions/setup-python@v2
       with:
         python-version: ${{ inputs.python-version }}

     - uses: Install twine
       run: |
         pip install --progress-bar off twine

     - name: Upload dist files to the test PyPI
       env:
         TWINE_PASSWORD: ${{ secrets.pypi-token }}
         TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
       run: |
         twine upload dist/*

  # upload: