name: Project stats
run-name: Project stats for ${{ inputs.pypi-name }}

on:

  workflow_dispatch:
    inputs:

      pypi-name:
        description: Name of the package distribution on PyPI
        default: ccsi-foqus
        required: false
        type: string

      start-date:
        description: Start date in YYYY-MM-DD format
        type: string
        required: true

      end-date:
        description: End date in YYYY-MM-DD format
        type: string
        required: false
        default: ''

jobs:
  pypi-download-counts:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./release/project-stats
        with:
          pypi-name: ${{ inputs.pypi-name }}
          start-date: ${{ inputs.start-date }}
          end-date: ${{ inputs.end-date }}
