name: Release (test)

on:
  workflow_dispatch:
    inputs:
      python-name:
        description: Name of the Python package distribution
        required: true
        type: choice
        options:
        - idaes-pse
        - watertap
        - dispatches
        - ccsi-foqus
        default: idaes-pse
      release-tag:
        description: Version tag of the release
        type: string
        required: false
        default: '1.0.0'


jobs:

  capture-env:
    name: Capture env
    runs-on: ubuntu-latest
    steps:
      - uses: lbianchi-lbl/actions/release/capture-env@main
        with:
          pypi-name: ${{ inputs.python-name }}
          pypi-version: ${{ inputs.release-tag }}
          python-version: '3.9'
          upload-artifact: ${{ inputs.python-name }}-${{ inputs.release-tag }}
