name: Release (test)

on:
  workflow_dispatch:

    inputs:

      project-id:
        description: Identifier for the project to release
        required: true
        type: choice
        options:
        - idaes
        - watertap
        - dispatches
        - ccsi-foqus
        - pareto

      release-tag:
        description: Version tag of the release
        type: string
        required: true

jobs:

  create-package:
    strategy:
      fail-fast: true
      matrix:
        project:
          - ${{ inputs.project-id }}
        include:
          - project: idaes
            repository: IDAES/idaes-pse
            pypi-name: idaes-pse
            test-command: idaes get-extensions --extra petsc --verbose && pip install pytest && wget https://raw.githubusercontent.com/IDAES/idaes-pse/main/pytest.ini && pytest --pyargs idaes -m "not integration" -x
    uses: ./.github/workflows/create-package.yml
    with:
      release-tag: ${{ inputs.release-tag }}
      repository: ${{ matrix.repository }}
      pypi-name: ${{ matrix.pypi-name }}
      test-command: ${{ matrix.test-command }}
    secrets:
      test-pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
      pypi-token: ${{ secrets.PYPI_TOKEN }}

  capture-env:
    if: false
    name: Capture env
    runs-on: ubuntu-latest
    steps:
      - uses: lbianchi-lbl/actions/release/capture-env@main
        with:
          pypi-name: ${{ inputs.python-name }}
          pypi-version: ${{ inputs.release-tag }}
          python-version: '3.9'
          upload-artifact: ${{ inputs.python-name }}-${{ inputs.release-tag }}
